// lib/seed-startups.ts
import { Startup } from '@/types/startup';

export const seedStartups: Omit<Startup, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'TechVision AI',
    slug: 'techvision-ai',
    description: 'Building next-generation AI tools for enterprise automation and workflow optimization.',
    fullDescription: 'TechVision AI is revolutionizing enterprise automation with cutting-edge AI solutions. Our platform helps businesses automate complex workflows, reduce operational costs, and improve efficiency by 10x. We serve Fortune 500 companies across various industries.',
    industry: 'AI/ML',
    size: '11-50',
    fundingStage: 'Series A',
    foundedDate: '2022-03-15',
    location: 'San Francisco, CA',
    websiteUrl: 'https://techvision-ai.example.com',
    jobCount: 8,
    logoUrl: '/logos/techvision.png',
    featured: true
  },
  {
    name: 'FinFlow',
    slug: 'finflow',
    description: 'Digital banking platform for SMBs with integrated accounting and payment solutions.',
    fullDescription: 'FinFlow provides a comprehensive digital banking solution tailored for small and medium-sized businesses. Our platform integrates banking, accounting, and payment processing into one seamless experience, helping businesses manage their finances more efficiently.',
    industry: 'FinTech',
    size: '51-200',
    fundingStage: 'Series B',
    foundedDate: '2020-06-20',
    location: 'New York, NY',
    websiteUrl: 'https://finflow.example.com',
    jobCount: 15,
    logoUrl: '/logos/finflow.png',
    featured: true
  },
  {
    name: 'HealthHub',
    slug: 'healthhub',
    description: 'Telemedicine platform connecting patients with healthcare providers worldwide.',
    fullDescription: 'HealthHub is democratizing healthcare access through our innovative telemedicine platform. We connect patients with qualified healthcare providers for virtual consultations, prescription management, and ongoing care coordination.',
    industry: 'HealthTech',
    size: '201-500',
    fundingStage: 'Series C',
    foundedDate: '2019-01-10',
    location: 'Boston, MA',
    websiteUrl: 'https://healthhub.example.com',
    jobCount: 23,
    logoUrl: '/logos/healthhub.png',
    featured: false
  },
  {
    name: 'EduPro',
    slug: 'edupro',
    description: 'AI-powered personalized learning platform for K-12 and higher education.',
    fullDescription: 'EduPro leverages AI to create personalized learning experiences for students of all ages. Our adaptive platform analyzes learning patterns and adjusts content delivery to maximize student engagement and outcomes.',
    industry: 'EdTech',
    size: '11-50',
    fundingStage: 'Seed',
    foundedDate: '2023-02-01',
    location: 'Austin, TX',
    websiteUrl: 'https://edupro.example.com',
    jobCount: 5,
    logoUrl: '/logos/edupro.png',
    featured: false
  },
  {
    name: 'ShopSmart',
    slug: 'shopsmart',
    description: 'AI-driven e-commerce platform with personalized shopping experiences.',
    fullDescription: 'ShopSmart is transforming online shopping with AI-powered personalization. Our platform analyzes customer behavior to provide tailored product recommendations, dynamic pricing, and seamless checkout experiences.',
    industry: 'E-commerce',
    size: '51-200',
    fundingStage: 'Series A',
    foundedDate: '2021-09-15',
    location: 'Seattle, WA',
    websiteUrl: 'https://shopsmart.example.com',
    jobCount: 12,
    logoUrl: '/logos/shopsmart.png',
    featured: true
  },
  {
    name: 'CloudOps Pro',
    slug: 'cloudops-pro',
    description: 'DevOps automation platform for cloud infrastructure management.',
    fullDescription: 'CloudOps Pro simplifies cloud infrastructure management with intelligent automation. Our platform helps DevOps teams deploy, monitor, and scale applications across multiple cloud providers with ease.',
    industry: 'DevTools',
    size: '11-50',
    fundingStage: 'Seed',
    foundedDate: '2022-11-20',
    location: 'Remote',
    websiteUrl: 'https://cloudops-pro.example.com',
    jobCount: 6,
    logoUrl: '/logos/cloudops.png',
    featured: false
  },
  {
    name: 'SecureNet',
    slug: 'securenet',
    description: 'Enterprise cybersecurity platform with AI-powered threat detection.',
    fullDescription: 'SecureNet provides comprehensive cybersecurity solutions for enterprises. Our AI-powered platform detects and responds to threats in real-time, protecting critical business assets and data.',
    industry: 'Cybersecurity',
    size: '201-500',
    fundingStage: 'Series B',
    foundedDate: '2018-04-05',
    location: 'Washington, DC',
    websiteUrl: 'https://securenet.example.com',
    jobCount: 18,
    logoUrl: '/logos/securenet.png',
    featured: true
  },
  {
    name: 'GreenEnergy Tech',
    slug: 'greenenergy-tech',
    description: 'Smart grid solutions for renewable energy management and optimization.',
    fullDescription: 'GreenEnergy Tech is building the future of sustainable energy. Our smart grid solutions optimize renewable energy distribution, reduce waste, and help utilities transition to cleaner energy sources.',
    industry: 'CleanTech',
    size: '51-200',
    fundingStage: 'Series A',
    foundedDate: '2021-03-10',
    location: 'Denver, CO',
    websiteUrl: 'https://greenenergy-tech.example.com',
    jobCount: 10,
    logoUrl: '/logos/greenenergy.png',
    featured: false
  }
];